name: Release

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    if: github.event_name == 'push' && startsWith(github.event.head_commit.message, '[REL]')
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/example-package-daemo/
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.11'
    - name: Install build dependencies
      run: python -m pip install -r build-requirements.txt
    - name: Build
      run: python -m build packaging_tutorial
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        packages-dir: packaging_tutorial/dist
